# Generated by Django 4.2.5 on 2024-01-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Notes',
        ),
    ]
